package com.app.general;

import java.time.Instant;
import java.util.UUID;

public record CrawlMaterializeJobResponse(
        UUID id,
        String sourceCode,
        String sourceName,
        String rootUrl,
        String sitemapUrl,
        String datasetId,
        String datasetPath,
        int maxUrls,
        boolean productOnly,
        boolean runQualityAudit,
        boolean runTaxonomyNormalize,
        boolean registerDataset,
        String stage,
        String stageMessage,
        Instant stageUpdatedAt,
        int totalUrls,
        int processedUrls,
        UUID tenantId,
        String visibility,
        boolean buildArtifact,
        boolean bindTenant,
        boolean importGeneral,
        UUID artifactId,
        String artifactPath,
        UUID activeKbVersionId,
        UUID generalSourceId,
        UUID importRunId,
        String status,
        int productCount,
        int ragChunkCount,
        String qualityStatus,
        String errorMessage,
        Instant createdAt,
        Instant startedAt,
        Instant finishedAt
) {
    public static CrawlMaterializeJobResponse from(CrawlMaterializeJob job) {
        return new CrawlMaterializeJobResponse(
                job.getId(),
                job.getSourceCode(),
                job.getSourceName(),
                job.getRootUrl(),
                job.getSitemapUrl(),
                job.getDatasetId(),
                job.getDatasetPath(),
                job.getMaxUrls(),
                job.isProductOnly(),
                job.isRunQualityAudit(),
                job.isRunTaxonomyNormalize(),
                job.isRegisterDataset(),
                job.getStage(),
                job.getStageMessage(),
                job.getStageUpdatedAt(),
                job.getTotalUrls(),
                job.getProcessedUrls(),
                job.getTenantId(),
                job.getVisibility(),
                job.isBuildArtifact(),
                job.isBindTenant(),
                job.isImportGeneral(),
                job.getArtifactId(),
                job.getArtifactPath(),
                job.getActiveKbVersionId(),
                job.getGeneralSourceId(),
                job.getImportRunId(),
                job.getStatus(),
                job.getProductCount(),
                job.getRagChunkCount(),
                job.getQualityStatus(),
                job.getErrorMessage(),
                job.getCreatedAt(),
                job.getStartedAt(),
                job.getFinishedAt()
        );
    }
}
