CREATE TABLE IF NOT EXISTS market_price_observations (
    id UUID PRIMARY KEY,
    tenant_id UUID NULL REFERENCES tenants(id) ON DELETE CASCADE,
    product_id VARCHAR(128),
    product_type VARCHAR(128) NOT NULL,
    name VARCHAR(255),
    material VARCHAR(128),
    dimensions VARCHAR(128),
    brand VARCHAR(128),
    condition VARCHAR(64),
    price NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(16) NOT NULL DEFAULT 'VND',
    source_name VARCHAR(255),
    source_url TEXT,
    confidence NUMERIC(4, 2) NOT NULL DEFAULT 0.70,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_price_observations_lookup
    ON market_price_observations (status, product_type, material, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_market_price_observations_product_id
    ON market_price_observations (product_id);

INSERT INTO market_price_observations (
    id, product_id, product_type, name, material, dimensions, brand, condition,
    price, currency, source_name, source_url, confidence, status, observed_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000101',
        'SFG041',
        'sofa',
        'Sofa gỗ sồi SFG041 - mẫu tham chiếu 1',
        'gỗ sồi',
        '2m x 0m9',
        'CaCo',
        'new',
        12000000,
        'VND',
        'CaCo catalog reference',
        'internal://market-price/SFG041-low',
        0.80,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000102',
        'SFG041',
        'sofa',
        'Sofa gỗ sồi SFG041 - mẫu tham chiếu 2',
        'gỗ sồi',
        '2m2 x 0m9',
        'CaCo',
        'new',
        15000000,
        'VND',
        'CaCo catalog reference',
        'internal://market-price/SFG041-high',
        0.80,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000103',
        'SOFA-GOC-L-01',
        'sofa',
        'Sofa góc chữ L bọc vải nỉ',
        'vải nỉ',
        '2m6 x 1m7',
        'CaCo',
        'new',
        12500000,
        'VND',
        'CaCo catalog reference',
        'internal://market-price/SOFA-GOC-L-01',
        0.70,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000104',
        'SOFA-GOC-L-02',
        'sofa',
        'Sofa góc chữ L da công nghiệp',
        'da công nghiệp',
        '2m8 x 1m8',
        'MOHO',
        'new',
        18900000,
        'VND',
        'MOHO catalog reference',
        'internal://market-price/SOFA-GOC-L-02',
        0.70,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000105',
        'BAN-AN-GO-01',
        'bàn ăn',
        'Bàn ăn gỗ sồi Nga 4 ghế',
        'gỗ sồi Nga tự nhiên',
        '1m4 x 0m8',
        'CaCo',
        'new',
        8500000,
        'VND',
        'CaCo catalog reference',
        'internal://market-price/BAN-AN-GO-01',
        0.70,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000106',
        'BAN-AN-GO-02',
        'bàn ăn',
        'Bàn ăn gỗ xoan đào 6 ghế',
        'gỗ xoan đào',
        '1m6 x 0m9',
        'MOHO',
        'new',
        14200000,
        'VND',
        'MOHO catalog reference',
        'internal://market-price/BAN-AN-GO-02',
        0.70,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000107',
        'GIUONG-1M6-01',
        'giường',
        'Giường ngủ gỗ MDF phủ Melamine 1m6',
        'gỗ MDF phủ Melamine',
        '1m6 x 2m',
        'CaCo',
        'new',
        6800000,
        'VND',
        'CaCo catalog reference',
        'internal://market-price/GIUONG-1M6-01',
        0.70,
        'ACTIVE',
        NOW()
    ),
    (
        '30000000-0000-4000-8000-000000000108',
        'TU-AO-01',
        'tủ quần áo',
        'Tủ quần áo 2 cánh gỗ công nghiệp',
        'gỗ MDF phủ Melamine',
        '1m2 x 2m',
        'MOHO',
        'new',
        5500000,
        'VND',
        'MOHO catalog reference',
        'internal://market-price/TU-AO-01',
        0.70,
        'ACTIVE',
        NOW()
    )
ON CONFLICT (id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    product_type = EXCLUDED.product_type,
    name = EXCLUDED.name,
    material = EXCLUDED.material,
    dimensions = EXCLUDED.dimensions,
    brand = EXCLUDED.brand,
    condition = EXCLUDED.condition,
    price = EXCLUDED.price,
    currency = EXCLUDED.currency,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    confidence = EXCLUDED.confidence,
    status = EXCLUDED.status,
    updated_at = NOW();
